
# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{?? DB? MBTI? ???? ?? ??? ?}?serverTimezone=Asia/Seoul
    username: DB ?? ??
    password: DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        # underscore to camelcase table name
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        # page? 1?? ???? ??
        one-indexed-parameters: true
        # page ???
        #        default-page-size: 10
        # ?? page ???
        max-page-size: 2000
  session:
    timeout: 86400
    jdbc:
      initialize-schema: always


logging.level:
  org.hibernate.SQL: debug

server:
  port: 3005

util:
  encrypt:
    secretKey:
  jwt:
    secretKey:
    refreshKey:
    defaultExpirationMinutes:
    defaultRefreshTokenMinutes: